### PR TITLE
Restructured project

### PR DESCRIPTION
**Pull request by MeekLogic**
PR for Issue #16
- Moved to Webpack for the build system
- Migrated loader definition to build system (targetting UMD)
- Moved to Ava for testing (ESM support)
- Split classes into modules
- Moved source files to src/
- Included template method for allowing variable includes
- Added polyfills through Babel with core-js
- Added ESLint to automate code styling (tried to match original formatting)

### CODE REVIEW

**Comment by MeekLogic** [comment]
Please let me know if you have any questions or concerns.

**Comment by MeekLogic** [comment]
Thanks for your feedback!

- Updated the readme with how to import the source files.
- Tested `require('n2words')` in a blank project with your latest n2words (from NPM) which I replaced the main script with the compiled version from my fork

NOTE: AMD require only worked under the namespace (n2words) and not when trying to use it in the tests file.

**Comment by MeekLogic** [comment]
Do you know what's the highest level ES you used?

**Comment by forzagreen** [comment]
Thank you very much for your work.
I've never got such great and complete pull request on GitHub !
I'll merge, then I'll release.
My next steps:
- To increase the coverage: 
  - either I'll run tests on the original source files
  - or I'll add browser tests (e.g. with puppeter)
- New languages are coming ;)

**Comment by forzagreen** [comment]
closes #16

**Comment by MeekLogic** [comment]
I agree that the coverage was an issue I was not able to sort out, just yet.

The issue I had was getting the coverage to work when running tests via the source modules vs the compiled results. The tests run just fine from source (via esm) and I intend to get coverage working for that as well.

**Pull request merged**
