### PR TITLE
Updates to project

### PR DESCRIPTION
**Pull request by TylerVigario**
- Drop tests for Node 10 & 11 (EOL)
- Add testing for Node 16
- Migrate to camelCase
- Fix all lint issues
- Update dependencies
- Update ESLint configuration

### CODE REVIEW

**Comment by TylerVigario** [comment]
How do you feel about switching to classes?

https://github.com/TylerVigario/n2words/blob/classes/lib/classes/N2WordsAbs.mjs
https://github.com/TylerVigario/n2words/blob/classes/lib/i18n/EN.mjs

**Review by forzagreen — APPROVED** [review]
Looks good for me.
Thank you for the amazing work !
I'll merge and release in the next few days ;)

**Comment by forzagreen** [comment]
@TylerVigario Regarding switching to class syntax, is it backward compatible ? do we need to drop some Node versions ?

**Comment by TylerVigario** [comment]
@forzagreen They introduced this class syntax alongside ES Modules so it's the same requirement as before.

I would like to bring up though that we haven't dropped compatibility with any Node versions for the compiled script. Right now, we compile the ES6+ source files to ES5 for the main script, which should have broad compatibility.

The requirement is only for working with the source files.

**Pull request merged**
