### PR TITLE
Fixed Serbian and Added Support for Croatian

### PR DESCRIPTION
**Pull request by lagavuliner**
Fixed errors mentioned in issue #60

### CODE REVIEW

**Comment by lagavuliner** [comment]
I've also added Croatian language support by adding a HR.mjs file. This is my first time using git to contribute to a project, please let me know if I've done it correctly.

**Review by forzagreen — CHANGES_REQUESTED** [review]
Thank you very much @lagavuliner  for your contribution !

Could you please add test cases for croatian and modify tests for serbian with the new expected values ? (cf. here: https://github.com/forzagreen/n2words/tree/master/test/i18n ).

Otherwise, there are other small modifications as in this PR https://github.com/forzagreen/n2words/pull/58 , but don't worry, I can modify them later.

**Comment by lagavuliner** [comment]
All is done in the "Corrected HR..." commit. Sorry for commit spam, I'm still grappling with git(hub) UI.

**Comment by forzagreen** [comment]
It's great ! thanks again @lagavuliner .
There are some small changes to do. I don't have permission to commit to your branch, so I created a PR in your fork: https://github.com/lagavuliner/n2words/pull/1 .

**Review by forzagreen — APPROVED** [review]

**Comment by forzagreen** [comment]
Fixes https://github.com/forzagreen/n2words/issues/60, released in [v1.11.0](https://github.com/forzagreen/n2words/releases/tag/v1.11.0)

**Pull request merged**
