### PR TITLE
Bump to 1.19

### PR DESCRIPTION
**Pull request by TylerVigario**

### CODE REVIEW

**Comment by forzagreen** [comment]
Hi @TylerVigario, Thank for the new updates !

Could you please build and push `package-lock.json` ? because the publish workflow gets the package version and dependencies from `package-lock.json` using `npm ci`:
https://github.com/forzagreen/n2words/blob/0ec8d63e26af779c4f02018b6135406b985cd992/.github/workflows/npm-publish.yml#L23

Also, there is an error in the step `npm run build:types`: https://github.com/forzagreen/n2words/actions/runs/7824354103
I am able to reproduce it locally, but I haven't had the opportunity to resolve it yet.
```
[node_modules/@types/node/globals.d.ts#L6](https://github.com/forzagreen/n2words/commit/e21496df297af90e7a0574937cbd3314c957889f#annotation_17828709934)
Cannot find module 'undici-types'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?
```

**Comment by TylerVigario** [comment]
I commit package-lock with dependency updates. See - https://github.com/forzagreen/n2words/pull/130

I'll take a look at the error in generating typings.

**Comment by forzagreen** [comment]
Make sure the package-lock.json contains the correct package version to be deployed (1.19.0)

**Comment by TylerVigario** [comment]
> Make sure the package-lock.json contains the correct package version to be deployed (1.19.0)

😆 That makes sense. I'll get that updated as well.

**Pull request merged**
