### PR TITLE
add isNumber function to util

### PR DESCRIPTION
**Pull request by MedoAngel**
this function is much safer than just using isNaN with Number because it rejects values like true, false,"" while Number accepts them as valid numbers

### CODE REVIEW

**Comment by TylerVigario** [comment]
Shouldn't we just use ES6 `Number.isNaN()`?

**Comment by MedoAngel** [comment]
no because isNaN('287349') is false and isNaN('foobar') is also false , which shouldn't be since '287349' is a string of a number.
 should i rename the function to isNumeric ? since I intend for it to allow string inputs that represent a number ?

**Comment by TylerVigario** [comment]
Apologies,  I should have made it clear that ES6's `Number.isNaN()` is different from `isNaN()`. It does not coerce a value to a number (like ES5's isNaN) and instead does strict type checking prior.

**Comment by TylerVigario** [comment]
@MedoAngel After looking at the source again (it's been a while) I like of the changes. It would be nice to get valid numbers from strings while rejecting invalid ones. Could we move the type checking to the entry function? I think it would be better to validate user input further up if possible.

https://github.com/forzagreen/n2words/blob/8f87b9a5f65927c215fc80a217dd5231f8afcda2/lib/n2words.mjs#L67

**Comment by MedoAngel** [comment]
image

still returns false for normal strings, even if it returned true based on the type not even being a number that would disallow numeric strings from passing . so in summary using isNaN would give false for true and false for '234324' and true for 'foobar' while Number.isNaN will give false on all of them

**Comment by TylerVigario** [comment]
> image
> 
> still returns false for normal strings, even if it returned true based on the type not even being a number that would disallow numeric strings from passing . so in summary using isNaN would give false for true and false for '234324' and true for 'foobar' while Number.isNaN will give false on all of them

I understand and agree that numeric values (even strings) should be accepted.

**Comment by MedoAngel** [comment]
> @MedoAngel After looking at the source again (it's been a while) I like the changes. It would be nice to get valid numbers from strings while rejecting invalid ones. Could we move the type checking to the entry function? I think it would be better to validate user input further up if possible.
> 
> https://github.com/forzagreen/n2words/blob/8f87b9a5f65927c215fc80a217dd5231f8afcda2/lib/n2words.mjs#L67

yes I agree will get right on it , would you like me to change the name as suggested to isNumeric ? and also add typeof checks to the function ?

**Comment by TylerVigario** [comment]
I agree that `isNumeric` seems more appropriate. We shouldn't need to enforce type checking anywhere else as long as we validate and convert to a number in the entry function.

**Comment by MedoAngel** [comment]
@TylerVigario done, changed and pushed

**Comment by TylerVigario** [comment]
@MedoAngel What would happen if we use "3px" as input? Since we use `parseFloat()` in the type checking but `Number()` [there are discrepancies](https://camchenry.com/blog/parsefloat-vs-number).

It seems the type checking would pass for "3px" but fail for the actual number initialization.

**Comment by MedoAngel** [comment]
@TylerVigario you're absolutely right, idk how i missed it, will modify the code later and look into other places where Number is used in the code base and see if it would be better using parseFloat instead

**Comment by TylerVigario** [comment]
Sounds good 👍

**Comment by MedoAngel** [comment]
> Sounds good 👍
> 
> **EDIT:** I too wonder if we should allow "3px" and similar inputs. 

I think we shouldn't , this wouldn't be number to words this would be parsing text for numbers then convert to words

**Comment by TylerVigario** [comment]
@MedoAngel Agreed, I think it will just cause issues outside our scope like with decimals and money.

**Comment by MedoAngel** [comment]
No decimals should still be parsed since the lib support that, but symbols unrelated to numbers should be rejected

**Comment by TylerVigario** [comment]
@MedoAngel I meant how decimals take on a bit of a different meaning when used in currencies. So disallowing all text (including currency symbols) would certainly help steer users away from trying to the use the library for money (which it's not currently designed to handle).

**Comment by MedoAngel** [comment]
> @MedoAngel I meant how decimals take on a bit of a different meaning when used in currencies. So disallowing all text (including currency symbols) would certainly help steer users away from trying to the use the library for currencies (which it's not currently designed to handle).

Yes Exactly

**Comment by MedoAngel** [comment]
@TylerVigario done with the changes we discussed earlier and added type checking just in case and for some speed improvement in case it's used on large data

**Comment by TylerVigario** [comment]
@MedoAngel Wouldn't it be simpler to do something like this?

```javascript
if (typeof value == 'number') return true;

if (typeof value != 'string') return false;

if (Number(value) == NaN) return false;

return true;
```

That would take care of the boolean issue and reduce the need to check for text in the value.

**Comment by MedoAngel** [comment]
No because typeof NaN is number which returns true

**Comment by TylerVigario** [comment]
@MedoAngel Added check for NaN

**Comment by TylerVigario** [comment]
@MedoAngel Added check for `NaN`

**Comment by MedoAngel** [comment]
> @MedoAngel Added check for `NaN`

Would still fail because '' is a string and Number('') is 0 so would return true

**Comment by TylerVigario** [comment]
> > @MedoAngel Added check for `NaN`
> 
> Would still fail because '' is a string and Number('') is 0 so would return true

True, however `parseFloat` doesn't parse leading white spaces.

**Comment by MedoAngel** [comment]
> > > @MedoAngel Added check for `NaN`
> > 
> > Would still fail because '' is a string and Number('') is 0 so would return true
> 
> True, however `parseFloat` doesn't parse leading white spaces.
> 
> **EDIT:** I wonder what's the use-case for allowing string types at all?

It does parse leading and trailing white space doesn't parse white space between two numbers which again isn't in our scope 


And i see that allowing strings would allow users to use the result directly from an input

**Comment by TylerVigario** [comment]
> It does parse leading and trailing white space doesn't parse white space between two numbers which again isn't in our scope

I didn't know that but is awesome and I agree that spaces between isn't within our scope.

> And i see that allowing strings would allow users to use the result directly from an input

Still arguably the responsibility of the application developer to ensure that string input gets properly converted to a number.

> Edit: and it's not even about allowing string types , it's about giving a more safe test for the value which previously allowed strings, null , undefined ..etc

It was already "safe" as it either inferred a number from the user input or gave a `TypeError`. This hasn't changed. This PR reduces that inference and does a bunch of checks to make sure text doesn't have any illegal characters (essentially everything but numbers).

**Comment by MedoAngel** [comment]
>It was already "safe" as it either inferred a number from the value or gave a TypeError. This PR reduces that inference and does a bunch of checks to make sure the text doesn't have any illegal characters.

Sorry, should've made it clear what I mean by type safe, I don't mean that the program crashes, what I mean is that it doesn't accept illogical input like ``` null, true``` ... etc, I think that if this PR doesn't get merged we should at least have a note at the read me page saying that this lib automatically infer type number from input and it's their responsibility to check for the input given

**Comment by TylerVigario** [comment]
@MedoAngel I totally agree that feeding n2words an empty string or `false` would produce "zero" in return which it should not. And I concede that this PR would improve that.

However, it probably won't improve things down the line for developers. For example; an application developer hooks their user input straight to this library without any validation. Previously they would get "zero" from an empty string but now it will throw a TypeError. Either way the application developer needs to handle that empty string situation within there application. Nothing we can do will absolve the application developer the responsibility of validating their user input.

**Comment by TylerVigario** [comment]
Resolved in #84. I wanted to merge this in but ultimately decided against it. I kept the logic within the `floatToCardinal` function and could avoid the overlapping `parseFloat` by trimming strings. Hopefully, there are no hard feelings. Thanks anyway!

**Pull request closed without merging**
