### PR TITLE
Added support for farsi language (fa)

### PR DESCRIPTION
**Pull request by omarius**

### CODE REVIEW

**Review by forzagreen — APPROVED** [review]
Great ! Thanks a lot !

**Comment by forzagreen** [comment]
@omarius I am currently working on adding support of decimal numbers and negative numbers.
Could you please tell me how to say "**point**" (1.1 == _one point one_) ? and how to say "**minus**" (-1 == _minus one_) in farsi ?

**Comment by omarius** [comment]
@forzagreen 
The persian word for point is:
ممیّز
and for negative numbers:
منفى
but numbers behind the decimal point are read differently.. I could adjust the function accordingly.

**Comment by forzagreen** [comment]
Thank you @omarius 

Here is a first version:
https://github.com/forzagreen/n2words/blob/23dc6574428b8f20428f823cdb1c52b4e09c3733/test/i18n/FA.mjs#L2-L9

It's based on this article: http://www.dastur.info/persian-grammar/6-numerals/6%E2%80%A21-counting-numerals/6%E2%80%A21%E2%80%A23-decimal-fraction-numerals/
(except for the case when having multiple leading zeros).

**Pull request merged**
