### PR TITLE
Have one distinct build file per language

### PR DESCRIPTION
**Pull request by ludans**
Some applications (well, mine actually) only require some languages.
Importing all of them for browser use is too heavy (93kb), while 1 file per language is lighter (30 to 40kb).
This PR builds, along the complete file, 1 file per language in dist/.

### CODE REVIEW

**Comment by TylerVigario** [comment]
The original idea was if they want a portion of it they would need to use WebPack themselves. I did this to keep the NPM package size small and to not try to make assumptions about the needs of the downstream users.

**Comment by ludans** [comment]
Thanks for your feedback.

Yes, this PR does not allow the selective inclusion but really just pre-packages each language individually.
I think it is easier, for a user, to point explicitly to a dedicated language specific language file rather than repackaging - maybe I'm wrong?
And I usually do not care that much about the package size on npm - but I can be wrong too.

(I use rollup)

I'm unsure about how I could remove unuseful stuff from an already precompiled package. Tree shake, probably, won't work.

I'll test tomorrow.

**Comment by TylerVigario** [comment]
You can easily include any of the language files directly.

```javascript
import Num2Word from './i18n/EN.mjs';
```

**Comment by ludans** [comment]
- It is possible to reference the .mjs file directly, as source code is included in the package, but I would say that it is a questionable practice.

- .mjs files cannot be included from TypeScript

- I can create something like that:

n2wordsWrapper.js
```JavaScript
const n2words = require('../../../node_modules/n2words/lib/i18n/EN.mjs');

exports.n2wordsEn = function (val) {
  return n2words(val, { lang: 'en' });
};
```
and include this file in my .ts files

(I don't like it: the path is weird in my mono repo)

- but then I have a usual `SyntaxError: Cannot use import statement outside a module`

- adding `"type": "module"` to my `package.json` (even if I don't want to) + run with  `--experimental-modules` (but I don't want to)

- I now get this error:
```
n2words/lib/classes/N2WordsAbs.mjs:7
  this.negative_word; //TODO: add support for negative words.
       ^

TypeError: Cannot read property 'negative_word' of undefined
```


Isn't all that a huge mess? What for? Just including the proper .js in dist should solve it all.

**Comment by TylerVigario** [comment]
You can certainly use modules in TypeScript - https://www.typescriptlang.org/docs/handbook/modules.html

As for the invalid reference it's due to the context `this` has. It's probably an issue with your RollUp config - https://github.com/rollup/rollup/issues/942

**Comment by TylerVigario** [comment]
I see `.cjs` and `.mjs` is a problem with TypeScript and there is an open issue to add support - https://github.com/microsoft/TypeScript/issues/27957

**Comment by TylerVigario** [comment]
If you can setup a repo with the minimal amount necessary to reproduce the issue I'd be glad to help further.

**Comment by ludans** [comment]
Thanks for your suggestions.

What I do currently:

- I have added my fork to my mono repo (fork called rosaenlg-n2words)
- in TypeScript I easily import just the language I need:
```
import n2words from '../../rosaenlg-n2words/dist/n2words_FR.js';
```
- I did not have to change my rollup config

and I end up with smaller packages - which was my sole target.

I will switch to mainstream n2words repo back once I can import easily mjs files in TypeScript. I don't except to do any modifications of n2words except this packaging part.

Feel free to accept or deny the PR. I can live with the fork (even if I will have to sync it manually with the main repo).

**Comment by TylerVigario** [comment]
I guess that would work for you but I don't believe your issue is caused by this package.

There should be absolutelty no need to consume the bundled versions if you are using a bundler in your own project. The vanilla (source) code runs on latest Node and Browsers without the need for modification. Even the tests are run on source files in Node as-is.

As for providing pre-built individual languages that are bundled and polyfilled which is probably only needed for older browsers is up to @forzagreen 

IMHO you should be building for your specific target environments and steer away from consuming polyfilled scripts.

**Comment by ludans** [comment]
I agree with the way of packaging.
I still think I'm stuck with TypeScript, probably during a few months.
I'll try to simplify my packaging process (and remove my forked version of n2words) in a few months.

**Comment by TylerVigario** [comment]
I believe you are on to something.

We should give concern to CommonJS users wanting only specific languages. Currently, our build process only creates a concatenated script that includes every language.

Interoperability between CJS and ESM is still murky water, and I will need to refine it. I will look at improving the dual environment package within the next couple months as well.

**Comment by TylerVigario** [comment]
I believe this to be the source of truth - https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

Correct me if Node doesn't set the standards.

I found this in the current documentation:
`Using require to load an ES module is not supported because ES modules have asynchronous execution. Instead, use use import() to load an ES module from a CommonJS module.`

_Yes, they doubly used "use". LOL_

**Comment by ludans** [comment]
thanks, I'm eager to see the solution (and integrate it)

**Comment by TylerVigario** [comment]
I successfully imported the ESM module via the [`import()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) function.

```javascript
// Dynamic Import
import('n2words/lib/n2words.mjs').then(n2words => {
    // Available via "default" function
    console.log(n2words.default(100));
}).catch(err => {
    // Catch dynamic import error
    console.error(err);
});
```

**Comment by ludans** [comment]
I have a very, very small package written in TypeScript and using n2words - actually only the Italian locale.

npm package is https://www.npmjs.com/package/italian-ordinals-cardinals
source is here https://github.com/RosaeNLG/rosaenlg/tree/master/packages/italian-ordinals-cardinals (in RosaeNLG mono repo)

I just can't make it work using standard version of n2words.

**Comment by TylerVigario** [comment]
I could use a forked version of TypeScript to resolve issues with `.mjs` files - https://github.com/stealify/typescript

**Comment by TylerVigario** [comment]
This should be closed IMHO

**Comment by forzagreen** [comment]
@ludans, There has been recently some work related to this topic by @TylerVigario 
Please check https://github.com/forzagreen/n2words/wiki/Importing-only-specific-languages

**Comment by ludans** [comment]
thanks for the notification
I made a test and have a typescript issue, see #109

**Pull request closed without merging**
